config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  with_options defaults: { format: :html } do
    resources :heros
    resources :abilities
  end
end

app/models/ability.rb
class Ability < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
end

app/models/path/safe_path.rb
module Path
  class SafePath
    attr_reader :controller, :method

    MATCHER = /^(\w*)_safe_path$/

    def initialize(controller, method)
      @controller = controller
      @method = method
    end

    def call_missing(*args)
      if MATCHER =~ method && does_respond_to?
        safe_path(*args)
      end
    end

    def does_respond_to?
      if MATCHER =~ method
        controller.respond_to?(path_method)
      end
    end

    private

    def path_method
      @path_method ||= MATCHER.match(method)[1]+'_path'
    end

    def safe_path(args)
      PathCaller.new(controller, path_method, args).path
    end
  end
end

app/models/path/safe_path/path_caller.rb
class Path::SafePath::PathCaller
  attr_reader :controller, :method, :args

  def initialize(controller, method, args)
    @controller = controller
    @method = method
    @args = args
  end

  def path
    controller_path.tap do |path|
      keys_map.each do |key, key_s|
        regexp = Regexp.new("\\b#{key_s}\\b")
        path.gsub!(regexp, args[key])
      end
    end
  end

  private

  def key_names
    @keys ||= args.keys.map { |k| "_#{k}" }
  end

  def keys_map
    @keys_map ||= key_names.as_hash(args.keys)
  end

  def controller_path
    @controller_path ||= controller.public_send(method, keys_map)
  end
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  include Common
  # GET /abilities
  # GET /abilities.json
  alias_method :index, :render_basic

  # GET /abilities/1
  # GET /abilities/1.json
  alias_method :show, :render_basic

  # GET /abilities/new
  def new
    render_basic
  end

  # GET /abilities/1/edit
  def edit
    render_basic
  end

  # POST /abilities
  # POST /abilities.json
  def create
    render json: created_ability.as_json
  end

  # PATCH/PUT /abilities/1
  # PATCH/PUT /abilities/1.json
  def update
    render json: updated_ability.as_json
  end

  # DELETE /abilities/1
  # DELETE /abilities/1.json
  def destroy
    ability.destroy
    head :no_content
  end

  private

  def new_json
    {}
  end

  def created_ability
    @created_ability ||= Ability.create(ability_params)
  end

  def updated_ability
    @updated_ability ||= ability.tap { |v| v.update(ability_params) }
  end

  def index_json
    Ability.all.as_json
  end

  def show_json
    ability.as_json
  end

  def ability
    @ability ||= Ability.find(ability_id)
  end

  def ability_id
    params.require(:id)
  end

  def ability_params
    params.require(:ability).permit(:name, :description, :is_ultimate)
  end

  alias_method :edit_json, :show_json
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def render_basic
    action = params[:action]
    respond_to do |format|
      format.json { render json: send("#{action}_json") }
      format.html { cached_render action }
    end
  end

  def not_found
    head :not_found
  end

  def cached_render(view)
    Rails.cache.fetch "render:#{params[:controller]}:#{view}" do
      render view
    end
  end
end

app/controllers/concerns/common.rb
module Common
  extend ActiveSupport::Concern
  include Tarquinn

  included do
    layout :layout_for_page
    redirection_rule :render_root, :perform_angular_redirect?
    skip_redirection_rule :render_root, :is_ajax?, :is_home?
  end

  private

  def render_root
    "##{request.path}"
  end

  def is_home?
    request.path == '/'
  end

  def is_ajax?
    params[:ajax]
  end

  def perform_angular_redirect?
    is_html?
  end

  def is_html?
    request.format.html?
  end

  def layout_for_page
    is_ajax? ? false : 'application'
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  include Common
  # GET /heros
  # GET /heros.json
  alias_method :index, :render_basic

  # GET /heros/1
  # GET /heros/1.json
  alias_method :show, :render_basic

  # GET /heros/new
  def new
    render_basic
  end

  # GET /heros/1/edit
  def edit
    render_basic
  end

  # POST /heros
  # POST /heros.json
  def create
    render json: created_hero.as_json
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    render json: updated_hero.as_json
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    hero.destroy
    head :no_content
  end

  private

  def new_json
    {}
  end

  def created_hero
    @created_hero ||= Hero.create(hero_params)
  end

  def updated_hero
    @updated_hero ||= hero.tap { |v| v.update(hero_params) }
  end

  def index_json
    Hero.all.as_json
  end

  def show_json
    hero.as_json
  end

  def hero
    @hero ||= Hero.find(hero_id)
  end

  def hero_id
    params.require(:id)
  end

  def hero_params
    params.require(:hero).permit(:name, :real_name, :health, :armor, :shield)
  end

  alias_method :edit_json, :show_json
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Common

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def angular_safe_link_to(path_method, path_args = {}, *args)
    link_to(
      angular_path_to(
        public_send("#{path_method.to_s.gsub(/(_path)?$/, '_safe_path')}", path_args)
      ),
      *args
    ) do
      yield
    end
  end

  def angular_path_to(path)
    "##{path}"
  end

  def method_missing(method, *args)
    Path::SafePath.new(self, method).call_missing(*args) || super
  end

  def respond_to?(method)
    return true if Path::SafePath.new(self, method).does_respond_to?
    super
  end

  def as_title(key)
    key.split('_').map(&:camelize).join(' ')
  end
end

app/views/abilities/_form.html.erb
<div ng-hide="controller.loaded">Loading ...</div>

<div ng-show="controller.loaded">
  <div class="col-md-3 col-sm-12">
    <div class="row">
      <div class="panel panel-default">

        <div class="panel-heading">New Hero</div>
        <div class="panel-body">

          <dl class="col-sm-12">
            <% %w(name description).each do |key| %>
              <div class="row">
                <dt><%= as_title(key) %></dt> <dd><input ng-model="controller.data.<%= [ base, key ].compact.join('.') %>"></dd>
              </div>
            <% end %>

            <div class="row">
              <dt>Ultimate?</dt> <dd>
              <select ng-model="controller.data.<%= [ base, :is_ultimate].compact.join('.') %> ">
                <option value="false">No</option>
                <option value="true">Yes</option>
              </select>
              </dd>
            </div>
          </dl>

          <div class="col-sm-12">
            <div class="row">
              <button ng-click="controller.save()" class="btn btn-default">Save</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/abilities/edit.html.erb
<%= render 'form', base: nil %>

app/views/abilities/index.html.erb
<div ng-hide="controller.loaded">Loading ...</div>

<div ng-show="controller.loaded">
  <div class="col-md-4 col-sm-12">
    <div class="row">

      <table class="table">
        <tr>
          <th>#</th>
          <% %w(name description ultimate? actions).each do |key| %>
            <th><%= as_title(key) %></th>
          <% end %>
        </tr>
        <tr ng-repeat="ability in controller.data">
          <td><a href="#/abilities/{{ ability.id }}">{{ ability.id }}</a></td>
          <% %w(name description is_ultimate).each do |key| %>
            <td>{{ ability.<%= key %> }}</td>
          <% end %>
          <td class="btn-group">
            <a class="btn btn-default" href='<%=
              angular_path_to(edit_ability_safe_path(id: '{{ ability.id }}'))
            %>'>Edit</a>
            <a class="btn btn-default" ng-click="controller.delete(hero.id)">Delete</a>
          </td>
        </tr>
      <table>

      <div class="col-sm-12">
        <div class="row">
          <a class="btn btn-default" href='<%= angular_path_to(new_ability_path) %>'>New</a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/abilities/new.html.erb
<%= render 'form', base: 'ability' %>

app/views/abilities/show.html.erb
<div ng-hide="controller.loaded">Loading ...</div>

<div ng-show="controller.loaded">
  <div class="col-md-2 col-sm-12">
    <div class="row">
      <div class="panel panel-default">

        <div class="panel-heading">{{ controller.data.name }}</div>
        <div class="panel-body">

          <dl>
            <% %w(id description).each do |key| %>
              <dt><%= as_title(key) %></dt> <dd>{{ controller.data.<%= key %> }}</dd>
            <% end %>
            <dt>Ultimate?</dt> <dd>{{ controller.data.is_ultimate }}</dd>
          </dl>
          <div class="col-sm-12">
            <div class="row">
              <a class="btn btn-default" href='<%= angular_path_to(abilities_path) %>'>Return</a>
              <a class="btn btn-default float-right" href='<%= 
                angular_path_to(
                  edit_ability_safe_path(
                    id: '{{ controller.data.id }}'
                  )
                )
              %>'>Edit</a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/heros/_form.html.erb
<div ng-hide="controller.loaded">Loading ...</div>

<div ng-show="controller.loaded">
  <div class="col-md-3 col-sm-12">
    <div class="row">
      <div class="panel panel-default">

        <div class="panel-heading">New Hero</div>
        <div class="panel-body">

          <dl class="col-sm-12">
            <% %w(name real_name health armor shield).each do |key| %>
              <div class="row">
                <dt><%= as_title(key) %></dt> <dd><input ng-model="controller.data.<%= [ base, key ].compact.join('.') %>"></dd>
              </div>
            <% end %>
          </dl>

          <div class="col-sm-12">
            <div class="row">
              <button ng-click="controller.save()" class="btn btn-default">Save</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/heros/edit.html.erb
<%= render 'form', base: nil %>

app/views/heros/index.html.erb
<div ng-hide="controller.loaded">Loading ...</div>

<div ng-show="controller.loaded">
  <div class="col-md-4 col-sm-12">
    <div class="row">

      <table class="table">
        <tr>
          <th>#</th>
          <% %w(name real_name health armor shield actions).each do |key| %>
            <th><%= as_title(key) %></th>
          <% end %>
        </tr>
        <tr ng-repeat="hero in controller.data">
          <td><a href="#/heros/{{ hero.id }}">{{ hero.id }}</a></td>
          <% %w(name real_name health armor shield).each do |key| %>
            <td>{{ hero.<%= key %> }}</td>
          <% end %>
          <td class="btn-group">
            <a class="btn btn-default" href='<%=
              angular_path_to(edit_hero_safe_path(id: '{{ hero.id }}'))
            %>'>Edit</a>
            <a class="btn btn-default" ng-click="controller.delete(hero.id)">Delete</a>
          </td>
        </tr>
      <table>

      <div class="col-sm-12">
        <div class="row">
          <a class="btn btn-default" href='<%= angular_path_to(new_hero_path) %>'>New</a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/heros/new.html.erb
<%= render 'form', base: 'hero' %>

app/views/heros/show.html.erb
<div ng-hide="controller.loaded">Loading ...</div>

<div ng-show="controller.loaded">
  <div class="col-md-2 col-sm-12">
    <div class="row">
      <div class="panel panel-default">

        <div class="panel-heading">{{ controller.data.name }}</div>
        <div class="panel-body">

          <dl>
            <% %w(id real_name health armor shield).each do |key| %>
              <dt><%= as_title(key) %></dt> <dd>{{ controller.data.<%= key %> }}</dd>
            <% end %>
          </dl>
          <div class="col-sm-12">
            <div class="row">
              <a class="btn btn-default" href='<%= angular_path_to(heros_path) %>'>Return</a>
              <a class="btn btn-default float-right" href='<%= 
                angular_path_to(
                  edit_hero_safe_path(
                    id: '{{ controller.data.id }}'
                  )
                )
              %>'>Edit</a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Overwatch</a>

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= angular_path_to(heros_path) %>">Heroes</a></li>
        <li><a href="<%= angular_path_to(abilities_path) %>">Abilities</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overwatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ng-app="overwatch">
    <%= render 'layouts/header' %>
    <div class="container-fluid" ng-view ng-controller="Global.Controller as gloc">
      <%= yield %>
    </div>
  </body>
</html>